services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle
    environment:
      BINDING: "0.0.0.0"
      BUNDLE_PATH: "/app/vendor/bundle"
    depends_on:
      - db
    tty: true

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
volumes:
  bundle:
  db:
