name: FrontEnd CI

on:
  pull_request:
    paths: 
      - 'app/frontend/**/*.{js,ts,vue}'
      - 'package.json'
      - 'package-lock.json'
  push:
    paths: 
      - 'app/frontend/**/*.{js,ts,vue}'
      - 'package.json'
      - 'package-lock.json'
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install npm
        run: npm ci

      - name: ESLint
        run: npm run lint
